-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : lun. 21 mars 2022 à 11:51
-- Version du serveur : 10.3.29-MariaDB-0+deb10u1
-- Version de PHP : 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `sae203`
--

-- --------------------------------------------------------

--
-- Structure de la table `manga`
--

CREATE TABLE `manga` (
  `manga_id` int(11) NOT NULL,
  `manga_titre` varchar(50) NOT NULL,
  `manga_prix` varchar(50) NOT NULL,
  `manga_annee` varchar(4) NOT NULL,
  `manga_resume` text NOT NULL,
  `manga_editeur` varchar(100) NOT NULL,
  `manga_photo` varchar(100) NOT NULL,
  `_auteur_id` int(130) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table manga';

--
-- Déchargement des données de la table `manga`
--

INSERT INTO `manga` (`manga_id`, `manga_titre`, `manga_prix`, `manga_annee`, `manga_resume`, `manga_editeur`, `manga_photo`, `_auteur_id`) VALUES
(2, 'Luffy versus la bande à Baggy !! - One Piece', '7,99 €', '2000', '\"Luffy et Zorro, qui poursuivent leur voyage, font la connaissance de Nami, \"\"la voleuse de pirates\"\", qui se trouve aux prises avec le clown pirate Baggy, qui possède une carte de la \"\"route de tous les périls\"\". Luffy décide alors de défier le terrible Baggy, détenteur lui aussi du pouvoir d\'un fruit du démon.\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '2.jpg', 1),
(3, 'Une Vérité qui blesse - One Piece', '7,99 €', '2001', 'Tout comme Luffy, Baggy le clown a mangé un fruit du démon. Le pirate peut ainsi séparer son corps en plusieurs morceaux et éviter la plupart des attaques qui le visent. Mais, lorsqu\'il plante ses lames dans le chapeau de Luffy, Baggy ignore la colère dont il va être la source…', '\"(ja) Shūeisha,  (fr) Glénat\"', '3.jpg', 1),
(4, 'Attaque au clair de lune - One Piece', '7,99 €', '2001', '\"Crow a pour projet d\'assassiner mademoiselle Kaya pour s\'approprier ses richesses ! Nos amis décident de se dresser sur sa route et aident Pipo à défendre le village des hommes d\'équipage du \"\"Chat noir\"\".\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '4.jpg', 1),
(5, 'Pour qui sonne le glas - One Piece', '7,99 €', '2001', '\"Suite et fin du combat contre Crow et l\'équipage du \"\"Chat noir\"\". A l\'issue du combat, nos amis obtiennent le \"\"Vogue Merry\"\", cadeau de mademoiselle Kaya. Nos amis reprennent l\'aventure en mer en direction du \"\"Baratie\"\", un navire restaurant, dans lequel ils espèrent trouver un cuisinier comme nouvelle recrue.\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '5.jpg', 1),
(6, 'Le Serment - One Pice ', '7,99 €', '2001', 'Luffy est obligé de travailler comme serveur pour rembourser les dégâts occasionnés au Baratie, Nami vamp Sandy, Sandy se prend la tête avec Pattie… Jusqu\'au moment où le Capitaine Creek guidé par Gyn, précédemment secouru par Sandy, arrive dans la place !', '\"(ja) Shūeisha,  (fr) Glénat\"', '6.jpg', 1),
(7, 'Vieux Machin - One Piece', '7,99 €', '2001', 'Les hommes de Krieg tiennent Zeff en otage et lui adressent une demande insensée ! La lâcheté de cet acte rend Luffy fou de rage mais Sanji l\'empêche de contre-attaquer.', '\"(ja) Shūeisha,  (fr) Glénat\"', '7.jpg', 1),
(8, 'Je ne mourrai pas ! - One Pice', '7,99 €', '2001', 'Ferme dans ses convictions et ignorant la peur, Luffy défie Don Krieg sans aucune hésitation. Ce combat mettra-t-il un terme à la bataille acharnée qui s\'est engagée sur le “Baratie” ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '8.jpg', 1),
(9, 'Larmes - One Piece', '7,99 €', '2002', ' À la poursuite de Nami, Luffy et son équipage arrivent à Arlong Park, sur les terres des hommes-poissons. C\'est là qu\'ils en apprendront plus sur le surprenant passé de leur navigatrice ! Dans la bataille solitaire qu\'elle mène depuis si longtemps, Nami saura-t-elle reconnaître ses vrais amis ?', '\"(ja) Shūeisha,  (fr) Glénat\"', '9.jpg', 1),
(10, 'Ok, let\'s stand up ! - One Piece', '7,99 €', '2002', 'Luffy s\'approche d\'Arlong en envoyant balader deux hommes poissons qui traînaient dans le coin avant de décocher un coup de poing magistral dans la poire d\'Arlong qui le fait décoller de son siège et se retrouve à plusieurs mètres de là. Ses trois autres compagnons arrivent en faisant le ménage derrière Luffy.', '\"(ja) Shūeisha,  (fr) Glénat\"', '10.jpg', 1),
(11, 'Le plus grand bandit d\'East Blue - One Piece', '7,99 €', '2002', 'Luffy est en mauvaise posture face aux crocs acérés du chef des hommes poisson : Arlong. Mais aidé de ses amis, notre homme caoutchouc parvient finalement à vaincre le tyran d\'Arlong Park.', '\"(ja) Shūeisha,  (fr) Glénat\"', '11.jpg', 1),
(12, 'Et ainsi débuta la légende - One Piece', '7,99 €', '2002', 'Après s\'être échappé de Loguetown, nos amis arrivent enfin sur la route de tous les périls ! Mais ils se font avaler par une gigantesque baleine. Ils y rencontrent une personne qui leur apprend l\'existence du log pose, le seul moyen de naviguer sans danger sur la mer de tous les périls', '\"(ja) Shūeisha,  (fr) Glénat\"', '12.jpg', 1),
(14, 'L\'Instinct - One Piece', '7,99 €', '2003', 'Luffy et son équipage sont arrivés à Little Garden, une île étrange sur laquelle deux géants poursuivent depuis 100 ans un seul et même combat, celui de la fierté des guerriers. Les membres de Baroque Works ne tardent pas à les y rejoindre pour semer leur pagaille !', '\"(ja) Shūeisha,  (fr) Glénat\"', '14.jpg', 1),
(15, 'Droit devant !! - One Piece', '7,99 €', '2003', 'Après leur bataille sur Little garden, nos amis reprennent la mer en direction d\'Alabasta. Mais Nami est terrassée par une forte fièvre, ce qui force léquipage du Vogue Merry à faire escale sur l\'île enneigée de Drum, pour y trouver un médecin.', '\"(ja) Shūeisha,  (fr) Glénat\"', '15.jpg', 1),
(16, 'Successeurs - One Piece ', '7,99 €', '2003', 'Luffy, Sanji et Nami ont survécu à l\'avalanche, mais le cuistot a perdu connaissance à son tour. Ce qui fait que Luffy pour atteindre le château du Docteur Kureha, doit escalader une gigantesque montagne avec ses deux compagnons sur le dos!! En arrivant au sommet, Luffy est tellement fatigué qu\'il lâche la paroi!!', '\"(ja) Shūeisha,  (fr) Glénat\"', '16.png', 1),
(17, 'Les Cerisiers d\'Hiluluk - One Piece', '7,99 €', '2003', 'Le combat fait rage entre Luffy et les troupes du roi Wapol. Chopper participe également à la bataille, bien décidé à se venger de ce roi à cause de qui il a perdu son mentor. Après un effroyable combat mené sur plusieurs fronts, l\'équipage du Vogue Merry et Chopper parviennent à vaincre leurs ennemis.', '\"(ja) Shūeisha,  (fr) Glénat\"', '17.png', 1),
(18, 'Ace entre en scène - One Piece', '7,99 €', '2003', 'Après avoir fait de nouvelles rencontres, l\'équipage du Vogue Merry arrive finalement à Alabasta. Nous en apprenons plus, grâce à un flash back, sur le passé de Vivi. En parallèle, l\'organisation secrète des Baroque Works réunit au grand complet ses membres les plus éminents.', '\"(ja) Shūeisha,  (fr) Glénat\"', '18.png', 1),
(19, 'Rébellion - One Piece', '7,99 €', '2004', 'Après avoir été mis au parfum sur la situation malheureuse du royaume d\'Alabasta, Luffy et ses amis se dirigent vers le repaire de Crocodile pour mettre un terme à ses projets de conquête.', '\"(ja) Shūeisha,  (fr) Glénat\"', '19.png', 1),
(20, 'Bataille décisive à Alaburna - One Piece', '7,99 €', '2004', ' Luffy décide de se battre seul contre Crocodile, pour laisser le temps à ses compagnons de se rendre à la capitale d\'Alabasta. Mais Crocodile étant fait de sable, aucune des attaques de Luffy ne l\'atteint : c\'est comme si Luffy se battait contre du vide.', '\"(ja) Shūeisha,  (fr) Glénat\"', '20.jpg', 1),
(21, 'Utopie - One Piece', '7,99 €', '2004', 'Enfin arrivée au palais royal, Vivi tombe nez à nez avec Crocodile, qui lui révèle le véritable objectif de son plan !! Pendant ce temps, l\'équipage poursuit son combat contre les agents de Baroque Works et fait face à leurs terribles pouvoirs !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '21.jpg', 1),
(22, 'Hope ! - One Piece', '7,99 €', '2004', 'Alors qu\'une explosion est sur le point de souffler la grande esplanade du palais royal, Luffy parvient enfin à retrouver Crocodile !! Il lui faut absolument remporter ce combat décisif pour mettre un terme à la rébellion qui secoue le royaume d\'Alabasta !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '22.jpg', 1),
(23, 'L\'Aventure de Vivi - One Piece', '7,99 €', '2004', 'Luffy, un garçon espiègle, rêve de devenir leur roi en trouvant le « One Piece », un fabuleux trésor. Par mégarde, Luffy a avalé un jour un fruit démoniaque qui l\'a transformé en homme-caoutchouc. Depuis, il est capable de se contorsionner et de s\'étirer grâce à son corps élastique, mais il a perdu la faculté de nager.', '\"(ja) Shūeisha,  (fr) Glénat\"', '23.jpg', 1),
(24, 'Croire en ses rêves - One Piece ', '7,99 €', '2004', 'Luffy et ses amis ont quitté Alabasta et s\'apprêtent à poursuivre leur périple. Mais un personnage inattendu fait son apparition sur le bateau !! À peine remis de leurs émotions, nos héros découvrent que selon le log pose, leur prochaine destination se situe… au-dessus des nuages !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '24.jpg', 1),
(25, 'L\'Homme qui valait 100 millions - One Piece', '7,99 €', '2005', '\"Après une longue discussion, il décide d\'aider Luffy à aller sur les îles célestes. Pendant que ses hommes se chargent de préparer le Vogue Merry pour la \"\"traversée\"\", Luffy et les autres se rendent dans la forêt pour trouver un oiseau du sud, indispensable à leur périple.\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '25.png', 1),
(26, 'Aventure sur l\'île de Dieu - One Piece', '7,99 €', '2005', 'Après une ascension digne du décollage d\'une fusée spatiale, l\'équipage du Chapeau de Paille se réveille sur une mer de nuages : il s\'agit de la Mer de Nuages. Mais ils ont à peine le temps d\'admirer le paysage et de tuer quelques monstres que surgit un indigène qui étale très facilement Luffy, Zoro et Sanji.', '\"(ja) Shūeisha,  (fr) Glénat\"', '26.jpg', 1),
(27, 'Prélude - One Piece', '7,99 €', '2005', 'Accusés d\'avoir pénétré clandestinement sur l\'île céleste et contraints de subir le jugement divin, Luffy et ses amis donnent tout ce qu\'ils ont dans le combat qui les oppose au premier prélat !! Ce n\'est qu\'après l\'affrontement qu\'ils seront amenés à découvrir la vérité la mieux gardée de l\'île…', '\"(ja) Shūeisha,  (fr) Glénat\"', '27.png', 1),
(28, 'Wiper le démon furieux - One Piece', '7,99 €', '2005', 'Parti à la recherche de la cité d\'or sur Upper Yard, l\'équipage du “Vogue Merry” se retrouve impliqué dans un combat qui ne devrait pas être le sien : celui des Shandia tentant de regagner leur terre natale aujourd\'hui sous l\'emprise d\'Ener.', '\"(ja) Shūeisha,  (fr) Glénat\"', '28.jpg', 1),
(29, 'Oratorio - One Piece', '7,99 €', '2005', 'La bataille qui oppose l\'équipage du “Vogue Merry”, les Shandia et les hommes d\'Ener avec ce dernier à leur tête sur Upper Yard atteint son paroxysme !! La prédiction d\'Ener comme quoi ils ne seront plus que cinq à tenir encore debout après trois heures passées sur l\'île va-t-elle se révéler juste ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '29.jpg', 1),
(30, 'Capriccio - One Piece', '7,99 €', '2006', ' Face au terrifiant dieu Ener, les combattants sont à bout de forces et baissent les armes les uns après les autres. C\'est à se demander s\'il n\'est pas déjà trop tard pour empêcher ce monstre de réaliser ses projets…', '\"(ja) Shūeisha,  (fr) Glénat\"', '30.png', 1),
(31, 'Nous sommes là - One Piece', '7,99 €', '2006', 'Au milieu de la fureur du ciel, Wiper se souvient des paroles de leur Chef au sujet de Calgara le Grand Guerrier. Débute alors un flash-back des événements qui se sont déroulés il y a 400 ans. En ce temps leur patrie se trouvait encore sur la Mer Bleue et Calgara la protégeait des intrus venant du grand océan.', '\"(ja) Shūeisha,  (fr) Glénat\"', '31.jpg', 1),
(32, 'Love Song - One Piece', '7,99 €', '2006', 'L\'amiral Aokiji, l\'un des hommes le plus fort de la Marine prend en chasse Luffy. Et nos amis prennent la décision de recruter un ingénieur naval ! Au cours d\'une tempête, ils croisent un drôle d\'équipage pirate où il n\'y a ni capitaine, ni navigateur... Ils finissent par arriver sur une étrange île où tout est long.', '\"(ja) Shūeisha,  (fr) Glénat\"', '32.jpg', 1),
(33, 'Davy Back Fight !! - One Piece', '7,99 €', '2006', 'Le “Davy Back Fight” est un jeu terrifiant où l\'on risque de perdre ses compagnons ! Mis au défi par l\'équipage de Foxy, et sans se douter un seul instant de ce qui les attend, Chapeau de paille et ses amis acceptent de participer à ce manège imprévisible !', '\"(ja) Shūeisha,  (fr) Glénat\"', '33.jpg', 1),
(34, 'Water Seven, la cité sur l\'eau - One Piece', '7,99 €', '2006', 'Après avoir accosté sur l\'île, Nami, Usopp et Luffy débarquent en premiers : ils vont échanger les trésors de Skypiea contre de l\'argent et ensuite ils se rendront sur un chantier de constructions navales. Grâce à Nami ils obtiendront 300 millions de Berry de leurs trésors.', '\"(ja) Shūeisha,  (fr) Glénat\"', '34.jpg', 1),
(35, 'Capitaine - One Piece', '7,99 €', '2006', 'Luffy et Usopp s\'affrontent violemment au sujet de la réparation du “Vogue Merry”. À l\'issue d\'un combat déchirant, le capitaine Luffy prend une décision des plus surprenantes ! L\'équipage va-t-il survivre à cette épreuve ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '35.jpg', 1),
(36, 'Justice N°9 - One Piece', '7,99 €', '2007', 'C\'est le bordel : les charpentiers s\'en prennent à Luffy qui ne comprend pas pourquoi. Ils lui révèlent que ce serait Robin qui aurait tiré sur Icebarg, mais Luffy ne peut y croire ! La situation dégénère et Luffy doit faire face aux 5 Maîtres Charpentiers en même temps!', '\"(ja) Shūeisha,  (fr) Glénat\"', '36.jpg', 1),
(37, 'Tom - One Piece', '7,99 €', '2007', 'Luffy et ses amis vont-ils affronter les membres du CP9 pour éviter que Robin ne quitte l\'équipage à jamais ?! Ces derniers se rendent chez Franky pour s\'emparer des plans de l\'arme antique “Pluton”, mais c\'est alors qu\'une terrible vérité éclate au grand jour !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '37.jpg', 1),
(38, 'Rocketman ! - One Piece', '7,99 €', '2007', 'Sanji est monté à bord du train des mers afin de secourir Robin. De son côté, sur l\'île menacée par l\'aqua laguna, le reste de l\'équipage est parti à la recherche de Luffy et de Zoro. Où ont-ils bien pu passer ?! Leurs amis doivent faire vite car la tempête est proche…', '\"(ja) Shūeisha,  (fr) Glénat\"', '38.jpg', 1),
(39, 'Compétition - One Piece', '7,99 €', '2007', '\"L\'équipe formée par Sanji, Franky et Sniper King entre en action : ils commencent par piéger un groupe d\'hommes menés par le Colonel T-Bone en détachant un Wagon du Puffing Tom ! Dans le wagon suivant nos amis font le \"\"ménage\"\" et Franky en profite pour leur faire une petite démonstration de ses talents cachés.\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '39.jpg', 1),
(40, 'Gear - One Piece', '7,99 €', '2007', 'Luffy et ses alliés ont débarqué sur l\'île judiciaire dans le but de récupérer leurs compagnons. Le combat promet d\'être rude cependant, car c\'est une véritable armée qu\'ils trouvent en face d\'eux ! De son côté, Luffy affronte Blueno, un agent du CP9.', '\"(ja) Shūeisha,  (fr) Glénat\"', '40.jpg', 1),
(41, 'Déclaration de guerre - One Piece', '7,99 €', '2008', ' Il y a 20 ans, sur une île de West Blue nommée Ohara, vivait une jeune fille triste et seule que les gens prenaient pour un monstre. Son nom : Nico Robin. Qu\'a-t-elle dû endurer par le passé pour se retrouver ainsi plongée dans le désespoir ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '41.jpg', 1),
(42, 'Les Pirates contre le CP9 - One Piece', '7,99 €', '2008', 'Luffy et ses camarades viennent de pénétrer dans la tour judiciaire mais le commandant Spandam a donné l\'ordre de les exterminer ! Réussiront-ils à se débarrasser des agents du CP9 et à sauver Robin ?! L\'affrontement entre l\'équipage de Chapeau de paille et le CP9 est sur le point de commencer !', '\"(ja) Shūeisha,  (fr) Glénat\"', '42.jpg', 1),
(43, 'La Légende du héros - One Piece', '7,99 €', '2008', ' Un buster call a été déclenché et Robin se rapproche dangereusement du point de non-retour que représente la porte de la justice ! Pris dans une course contre la montre, Luffy et ses compagnons réussiront-ils à se débarrasser du CP9 et à sauver leur amie du désespoir ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '43.jpg', 1),
(44, '\"\"\"Rentrons\"\" - One Piece\"', '7,99 €', '2008', 'L\'équipage de Chapeau de paille rejoint Robin et se met à la recherche d\'un moyen de quitter Enies Lobby. Mais le temps presse car le déclenchement du “buster call” plonge l\'île dans le chaos le plus total ! Pendant ce temps, Luffy s\'engage dans un combat sans merci contre Lucci.', '\"(ja) Shūeisha,  (fr) Glénat\"', '44.jpg', 1),
(45, 'Je comprends ce que vous ressentez - One Piece', '7,99 €', '2008', 'La bataille d\'Enies Lobby est enfin terminée. Mais alors que Franky leur fabrique un nouveau bateau, Luffy et ses amis reçoivent la visite d\'un personnage pour le moins inattendu ! Pendant ce temps, Pipo réfléchit à la meilleure façon de réintégrer l\'équipage.', '\"(ja) Shūeisha,  (fr) Glénat\"', '45.jpg', 1),
(46, 'Aventure sur l\'île fantôme - One Piece', '7,99 €', '2008', 'Alors qu\'il se dirige vers l\'île des hommes-poissons à bord de son nouveau navire, l\'équipage de Luffy est pris dans une tempête et pénètre contre son gré dans le “Triangle de Florian”. Il y fait la rencontre d\'un curieux personnage à qui Luffy s\'empresse de faire une proposition stupéfiante !', '\"(ja) Shūeisha,  (fr) Glénat\"', '46.jpg', 1),
(47, 'Temps couvert avec chutes d\'os par moments - One P', '7,99 €', '2009', 'Brook qui s\'est fait voler son ombre, Nami, Pipo et Chopper qui se font agresser par des zombies, et les autres membres de l\'équipage qui disparaissent un à un… Thriller Bark est le théâtre d\'une suite d\'événements inexplicables !', '\"(ja) Shūeisha,  (fr) Glénat\"', '47.jpg', 1),
(48, 'L\'Aventure d\'Oz - One Piece', '7,99 €', '2009', 'Luffy et son équipage se lancent de nouveau à l\'assaut de Thriller Bark afin de récupérer avant le lever du jour les ombres que Moria leur a volées. Mais les quatre mystérieux, l\'armée des généraux zombies et Oz le démon qui abrite l\'ombre de Chapeau de paille vont tout faire pour les en empêcher !', '\"(ja) Shūeisha,  (fr) Glénat\"', '48.jpg', 1),
(49, 'Nightmare Luffy - One Piece', '7,99 €', '2009', 'Nos héros pirates unissent leurs compétences pour affronter le démon Odz, et ils parviennent à le maîtriser. Mais lorsque Hogback se met à piloter le démon de l\'intérieur, plus personne ne semble en mesure de l\'arrêter.', '\"(ja) Shūeisha,  (fr) Glénat\"', '49.jpg', 1),
(50, 'De nouveau face au mur - One Piece', '7,99 €', '2009', 'Bien qu’il ait dépassé ses limites et soit quasiment à bout de forces, Luffy utilise son “gear” pour tenter de s’opposer à un Moria devenu ultra-puissant après s’être gavé de 1000 ombres ! La bataille acharnée de Thriller Bark touche à sa fin ! Les aventures de Luffy à la poursuite du One Piece continuent !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '50.jpg', 1),
(51, 'Les Onze Supernovae - One Piece', '7,99 €', '2009', 'Sur le chemin de l\'île des hommes-poissons, l\'équipage de Chapeau de paille fait escale sur l\'archipel des Sabaody, des îles étranges où flottent des bulles de savon et où se perpétue une tradition très ancienne !', '\"(ja) Shūeisha,  (fr) Glénat\"', '51.jpg', 1),
(52, 'Roger & Rayleigh - One Piece', '7,99 €', '2010', 'L’équipage de Chapeau de paille est poursuivi par la Marine pour avoir frappé un dragon céleste ! Une bataille acharnée s’engage alors entre les “nouveaux venus” et les innombrables soldats envoyés en renfort sur les lieux ! Pour finir, l’archipel se transforme en une véritable mer de flammes quand débarque l’amiral “Kizaru”… Les aventures de Luffy à la poursuite du One Piece continuent !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '52.jpg', 1),
(53, 'Le Tempérament d\'un roi - One Piece', '7,99 €', '2010', 'Après Zoro, Kuma fait disparaître le reste de l\'équipage sous les yeux d\'un Luffy impuissant. Puis il fait disparaître à son tour ce dernier ! Après un long voyage dans le ciel, Luffy atterrit sur une mystérieuse île qui se révèle uniquement peuplée de femmes !', '\"(ja) Shūeisha,  (fr) Glénat\"', '53.jpg', 1),
(54, 'Plus personne ne m\'arrêtera - One Piece', '7,99 €', '2010', 'Alors que la mise à mort publique d\'Ace approche dangereusement, Luffy prend la route d\'Impel Down, la prison sous-marine, avec l\'aide de Boa Hancock. Malgré les mesures drastiques de sécurité et le nombre impressionnant de gardiens, il a bien l\'intention d\'en libérer son frère !', '\"(ja) Shūeisha,  (fr) Glénat\"', '54.jpg', 1),
(55, 'Des Travs en enfer - One Piece', '7,99 €', '2010', 'L\'assaut de la prison d\'Impel Down par Luffy continue. Ce dernier se retrouve en très grande difficulté face au directeur Magellan et son pouvoir terrifiant. Mais un de ses ex-ennemis de Baroque Works, libérés en chemin, lui apporte un soutient inestimable.', '\"(ja) Shūeisha,  (fr) Glénat\"', '55.jpg', 1),
(56, 'Merci pour tout - One Piece', '7,99 €', '2011', 'Luffy et les évadés d\'Impel Down se lancent à la poursuite d\'Ace, qui a été conduit à Marine Ford. Malheureusement, le chemin se révèle semé d\'embûches… Pendant ce temps, un homme s\'apprête à révéler un secret susceptible d\'ébranler le monde entier. Les aventures de Luffy à la poursuite du One Piece continuent !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '56.png', 1),
(57, 'Guerre au sommet - One Piece', '7,99 €', '2011', 'En attente d\'être exécuté, Ace se remémore sa rencontre avec Shanks le Roux. C\'est alors qu\'arrive Barbe Blanche, entouré de pirates et de corsaires ! Face à eux, la Marine déploie ses amiraux et une bataille titanesque commence !', '\"(ja) Shūeisha,  (fr) Glénat\"', '57.jpg', 1),
(58, 'L\'Ère de Barbe Blanche - One Piece', '7,99 €', '2011', 'Blessé par l\'un des siens, Barbe Blanche est amoindri. Quelles répercussions cet événement imprévu aura-t-il sur la bataille ?! De son côté, Luffy s\'élance au secours d\'Ace, mais les plus redoutables généraux lui barrent la route !', '\"(ja) Shūeisha,  (fr) Glénat\"', '58.jpg', 1),
(59, 'La Mort de Portgas D. Ace - One Piece', '7,99 €', '2011', 'Luffy a bravé mille dangers pour libérer son frère Portgas D. Ace des griffes de la marine. Il a reçu le soutien inopiné de Barbe Blanche, bien décidé à assister à ce que promettait la nouvelle génération. Il a même réussi à ôter les chaînes en granit marin de son frère, lui rendant ses pouvoirs de fruit du démon !', '\"(ja) Shūeisha,  (fr) Glénat\"', '59.jpg', 1),
(60, 'Petit frère - One Piece', '7,99 €', '2012', '\"Ce tome 60 intitulé \"\"Petit Frère\"\" revient sur l\'enfance de Monkey D. Luffy, fils de Dragon le leader de la révolution mondiale, Portgas D. Ace fils de Gol D. Rogers le Seigneur des Pirates, et Sabo fils de noble qui a choisi la vivre pauvre mais livre plutôt que riche et asservi par la ploutocratie mondiale !\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '60.jpg', 1),
(61, 'À l\'aube d\'une grande aventure dans le Nouveau Mon', '7,99 €', '2012', 'Deux ans après la guerre au sommet, chacun des compagnons de Luffy a subi un entraînement spécifique et est dorénavant plus fort. Tous se retrouvent tous sur l\'île des Sabaody pour continuer leur aventure sur Grand Line.', '\"(ja) Shūeisha,  (fr) Glénat\"', '61.jpg', 1),
(62, 'Périple sur l\'île des hommes-poissons - One Piece', '7,99 €', '2012', 'Après une absence de deux ans, l\'équipage du Chapeau de paille est enfin réuni, provoquant une véritable pagaille sur l\'archipel des Sabaody où la Marine tente de les capturer ! Luffy et ses compagnons, qui retrouvent le Thousand Sunny intact, s\'élancent alors vers les abysses.', '\"(ja) Shūeisha,  (fr) Glénat\"', '62.jpg', 1),
(63, 'Otohime et Tiger - One Piece', '7,99 €', '2012', '\"Rien ne va plus sur l\'île des hommes-poissons. La princesse Shirahoshi, enfermé pendant dix ans dans une tour pour être protéger des attaques répétés de son \"\"prétendant\"\", a disparue ! Pire, la dernière personne a avoir été vu quittant sa chambre est Luffy !\"', '\"(ja) Shūeisha,  (fr) Glénat\"', '63.jpg', 1),
(64, '100 000 vs 10 - One Piece', '7,99 €', '2012', 'Les habitants de l\'île des hommes-poissons se rapprochent petit à petit de cet idéal de paix avec les hommes que leur a légué leur défunte reine. Mais Hody Jones et les New Fishman comptent bien briser ce rêve !! Luffy et son équipage, entraînés dans cette affaire, se lancent dans une lutte acharnée sur l\'île !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '64.jpg', 1),
(65, 'Table rase - One Piece', '7,99 €', '2013', 'L\'équipage du chapeau de paille tente d\'empêcher le pirate Hody Jones de s\'emparer de l\'île des hommes-poissons. Durant son combat sous-marin contre Luffy, Hody va commettre un nouveau crime atroce ! C\'est maintenant l\'existence même de l\'île des hommes-poissons qui est menacée par ce nouveau péril.', '\"(ja) Shūeisha,  (fr) Glénat\"', '65.jpg', 1),
(66, 'Vers le soleil - One Piece', '7,99 €', '2013', 'L\'île des hommes-poissons a décidé de tirer un trait sur ses vieilles rancœurs afin de nouer des liens avec les humains ! Cependant, ce jour de la réconciliation pourrait ne jamais arriver, car toute l\'île est menacée de destruction par Noah !', '\"(ja) Shūeisha,  (fr) Glénat\"', '66.jpg', 1),
(67, 'Cool Fight - One Piece', '7,99 €', '2013', 'Arrivé dans le Nouveau Monde, l\'équipage fait escale sur Punk Hazard, une île mystérieuse où règnent à la fois une chaleur infernale et un froid glacial, et sur laquelle se trouve un homme dont il ne reste que les jambes.', '\"(ja) Shūeisha,  (fr) Glénat\"', '67.jpg', 1),
(68, 'Alliance entre pirates - One Piece', '7,99 €', '2013', 'Luffy accepte la proposition de Law de former une alliance entre pirates. Les voilà partis pour affronter César Clown dans une course poursuite des plus folles !! Law entreprend d\'enlever César pour semer la panique dans son camp, mais une rencontre inattendue vient perturber ses plans !!', '\"(ja) Shūeisha,  (fr) Glénat\"', '68.jpg', 1),
(69, 'SAD - One Piece', '7,99 €', '2014', 'La situation devient critique : le gaz toxique “Morte-Terre” commence à s\'infiltrer dans le laboratoire ! Maintenant, Luffy et ses amis doivent non seulement capturer César Clown, mais aussi rejoindre la sortie au plus vite ! Réussiront-ils à contrecarrer les plans diaboliques de leurs adversaires ?!', '\"(ja) Shūeisha,  (fr) Glénat\"', '69.jpg', 1),
(70, 'Doflamingo sort de l\'ombre - One piece', '7,99 €', '2014', 'Alors que l\'équipage est sur le point de s\'échapper du laboratoire, César opère une prodigieuse transformation. Luffy parviendra-t-il à réduire à néant les ambitions de son adversaire ?! Il faudra aussi compter sur Doflamingo, le grand corsaire qui tire les ficelles, dont l\'apparition bouleverse la donne !', '\"(ja) Shūeisha,  (fr) Glénat\"', '70.jpg', 1),
(71, 'Le Colisée de tous les dangers - One Piece', '7,99 €', '2014', 'L\'équipage a pénétré dans le royaume de Dressrosa, dirigé par Doflamingo ! Parti détruire l\'usine de “smiles”, Luffy décide subitement de participer à un tournoi dont le vainqueur recevra un certain fruit du démon ! Les aventures de Luffy à la poursuite du One Piece continuent !', '\"(ja) Shūeisha,  (fr) Glénat\"', '71.jpg', 1),
(72, 'Les Oubliés de Dressrosa - One Piece', '7,99 €', '2014', 'Luffy finit par vaincre l\'ancien pirate et le choc de son attaque finale fait revenir sa bosse frontale que Garp avait fait disparaître à l\'époque ! Suite à cet événement inattendu Chinjao est finalement très reconnaissant envers Luffy et lui propose même de mettre la flotte d\'Happo à son service!', '\"(ja) Shūeisha,  (fr) Glénat\"', '72.jpg', 1),
(73, 'L\'Opération Dressrosa S.O.P. - One Piece', '7,99 €', '2015', 'Apres une intervention au visioescargophone du Royaume les citoyens acceptent sans réfléchir disant que leur roi est quelqu\'un de bien et qu \'il a ses raisons. Doflamingo use de son pouvoir pour manipuler le roi et le faire massacrer les citoyens, idem pour l\'armée, le royaume tout entier est proie à la terreur.', '\"(ja) Shūeisha,  (fr) Glénat\"', '73.jpg', 1),
(74, 'Je serai toujours à tes côtés - One Piece', '7,99 €', '2015', 'L\'armée des rebelles débute sa grande opération et s\'infiltre dans la Maison des Jouets via un tunnel qu\'ils ont creusé. En effet cette maison n\'est rien d\'autre que l\'usine, située sous le Colisée. Leur cible est Sugar, le membre de la famille Donquixote qui a le pouvoir de transformer en jouet.', '\"(ja) Shūeisha,  (fr) Glénat\"', '74.jpg', 1),
(102, 'Demon Slayer', '7,99 €', '2016', 'Un pauvre jeune homme découvre sa famille massacrée par un démon dans un recoin rural du Japon. Seule sa soeur s\'en est sortie mais pas indemne puisqu\'elle a elle-même été transformée en démon. Tanjiro va alors tout faire pour que sa soeur Nezuko redevienne humaine.', '\"	(ja) Shūeisha,  (fr) Panini\"', 'demonslayer.jpg', 2),
(103, 'Attaque des Titans', '7,99 €', '2009', 'Dans un monde ravagé par des titans mangeurs d\'homme depuis plus d\'un siècle, les rares survivants de l\'Humanité n\'ont d\'autre choix pour survivre que de se barricader dans une cité-forteresse.', '\"(ja) Kōdansha,  (fr) Pika Édition\"', 'snk.jpg', 3),
(104, 'Fire Force', '7,99 €', '2015', 'L\'humanité est terrifiée par le phénomène de combustion humaine. Des brigades spéciales Fire Force ont donc été mises en place avec pour mission de trouver la cause de ce mystérieux phénomène ! Le jeune Shinra, nouvelle recrue surnommée le Démon, rêve de devenir un héros.', '\"(ja) Kōdansha, (fr) Kana\"', 'fire force.jpg', 4),
(105, 'Black  Clover', '7,99 €', '2017', 'Dans un monde régi par la magie, Yuno et Asta ont grandi ensemble avec un seul but en tête : devenir le prochain Empereur-Mage du royaume de Clover. Mais si le premier est naturellement doué, le deuxième, quant à lui, ne sait pas manipuler la magie. C\'est ainsi que lors de la cérémonie d\'attribution de leur grimoire, Yuno reçoit le légendaire grimoire au trèfle à quatre feuilles tandis qu\'Asta, lui, repart bredouille. Or plus tard, un ancien et mystérieux ouvrage noir décoré d\'un trèfle à cinq feuilles surgit devant lui ! Un grimoire d’anti-magie...', '\"(ja) Shūeisha,  (fr) Kazé\"', 'blackclover.jpg', 5),
(106, 'Dragon Ball', '7,99 €', '1984', ' Les dragon balls sont des boules de cristal magiques. Celui qui les réunit invoque un dragon qui réalisera ses voeux. Sangoku, Dendé, Végéta et tous les protagonistes de cette grande saga tentent de trouver les sept dragon balls qui, une fois le voeu exaucé, s\'éparpilleront à nouveau dans l\'univers.', '\"(ja) Shūeisha,  (fr) Glénat\"', 'dragon ball.jpg', 6),
(107, 'Death Note', '7,99 €', '2003', 'Light Yagami ramasse un étrange carnet oublié dans la cour de son lycée. Selon les instructions du carnet, la personne dont le nom est écrit dans les pages du Death Note mourra dans les 40 secondes !! Quelques jours plus tard, Light fait la connaissance de l\'ancien propriétaire du carnet : Ryûk, un dieu de la mort !', '\"(ja) Shūeisha,  (fr) Kana\"', 'deathnote.jpg', 7),
(108, 'Haikyu', '7,99 €', '2012', 'En intégrant la section volley du lycée Karasuno, notre rookie est déterminé à prendre sa revanche sur Tobio, un passeur aussi arrogant que talentueux qui l\'avait humilié au collège. Mais, en ouvrant les portes du gymnase, il découvre que son ennemi juré est son futur coéquipier !', '\"(ja) Shūeisha,  (fr) Kazé\"', 'haikyu.jpg', 8),
(109, 'Naruto', '7,99 €', '1999', 'Dans le village de Konoha évit Naruto, le pire garnement de l\'école des ninjas ! Son passe temps favori ? Faire les quatre cents coups! Mais Naruto a aussi un rêve démesuré: devenir le plus puissant ninja de son village. Seulment voilà, un gran mystère plane autour de ce garçon...', '\"(ja) Shūeisha,  (fr) Kana\"', 'naruto.jpg', 9),
(110, 'Bleach', '7,99 €', '2001', 'Adolescent de quinze ans, Ichigo Kurosaki possède un don particulier : celui de voir les esprits. Un jour, il croise la route d\'une belle shinigami (un être spirituel) en train de pourchasser une “âme perdue”, un esprit maléfique qui hante notre monde et n\'arrive pas à trouver le repos.', '\"(ja) Shūeisha,  (fr) Glénat\"', 'bleach.jpg', 10),
(111, 'Baki', '7,99 €', '1999', 'Baki a ainsi été éduqué toute sa jeunesse pour devenir le plus fort, et marcher sur les traces de son père. Ce destin hors du commun l\'amène à chercher sans cesse un nouveau défi, un nouveau combat à mener, un nouvel adversaire à terrasser. Nombreux sont les guerriers qui croiseront sa route.', '\"(ja) Akita Shoten,  (fr) Delcourt\"', 'baki.jpg', 10);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `manga`
--
ALTER TABLE `manga`
  ADD PRIMARY KEY (`manga_id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `manga`
--
ALTER TABLE `manga`
  MODIFY `manga_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=112;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
